backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.json"
      format: "json"
      fields:
      
        - label: "Hero"
          name: "hero"
          widget: "object"
          summary: '{{fields.title}}'
          fields:
            - {label: "Heading", name: "heading", widget: "string"}
            - {label: "Subheading", name: "subheading", widget: "string"}
            - {label: "Background Image", name: "background_image", widget: "image"}
      