backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.json"
      format: "json"
      fields:
      
        - label: "Hero"
          name: "hero"
          widget: "object"
          summary: '{{fields.heading}}'
          collapsed: true
          fields:
            - {label: "Heading", name: "heading", widget: "string"}
            - {label: "Subheading", name: "subheading", widget: "string"}
            - {label: "Background Image", name: "background_image", widget: "image"}
            - {label: "Benefits icon", name: "benefits_icon", widget: "image"}
            - label: "Benefits"
              name: "benefits"
              widget: "list"
              fields:
                 - {label: "Title", name: "title", widget: "string"}
        - label: "Logos with Numbers"
          name: "numbers"
          widget: "object"
          collapsed: true
          fields:
            - label: "Number"
              name: "benefits"
              widget: "list"
              fields:
                 - {label: "Number", name: "number", widget: "string"}
                 - {label: "Image", name: "image", widget: "image"}
