backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.json"
      format: "json"
      fields:
      
        - label: "Hero"
          name: "hero"
          widget: "object"
          summary: '{{fields.heading}}'
          collapsed: true
          fields:
            - {label: "Heading", name: "heading", widget: "string"}
            - {label: "Subheading", name: "subheading", widget: "string"}
            - {label: "Background Image", name: "background_image", widget: "image"}
            - {label: "Benefits icon", name: "benefits_icon", widget: "image"}
            - label: "Benefits"
              name: "benefits"
              widget: "list"
              fields:
                 - {label: "Title", name: "title", widget: "string"}
        - label: "Logos with Numbers"
          name: "numbers"
          widget: "object"
          collapsed: true
          fields:
            - label: "Number"
              name: "numbers"
              widget: "list"
              fields:
                 - {label: "Number", name: "number", widget: "string"}
                 - {label: "Image", name: "image", widget: "image"}
                 - {label: "Name (alt text)", name: "name", widget: "string"}
        - label: "Images with text"
          name: "images_text"
          widget: "object"
          collapsed: true
          fields:
            - label: "Block"
              name: "block"
              widget: "list"
              summary: '{{fields.heading}}'
              fields:
                 - {label: "Image", name: "image", widget: "image"}
                 - {label: "Alt text", name: "alt_text", widget: "string"}
                 - {label: "Heading", name: "heading", widget: "string"}
                 - {label: "Description", name: "description", widget: "markdown"}
                 - {label: "CTA Text", name: "cta_text", widget: "string", default: "Contact Us"}
                 - {label: "Reverse", name: "reverse", widget: "boolean", default: false}

        - label: "Our clients"
          name: "ourClients"
          widget: "object"
          summary: '{{fields.heading}}'
          collapsed: true
          fields:
            - {label: "Heading", name: "heading", widget: "string"}
            - label: "Clients"
              name: "clients"
              widget: "list"
              fields:
                 - {label: "Image", name: "image", widget: "image"}
                 - {label: "Alt text", name: "alt_text", widget: "string"}
        - label: "Services"
          name: "services"
          widget: "object"
          collapsed: true
          fields:
            - label: "Service"
              name: "service"
              widget: "list"
              fields:
                 - {label: "Image", name: "image", widget: "image"}
                 - {label: "Alt text", name: "alt_text", widget: "string"}
                 - {label: "Heading", name: "heading", widget: "string"}
                 - {label: "Subheading", name: "subheading", widget: "string"}        
        - label: "Some Apps"
          name: "someApps"
          widget: "object"
          collapsed: true
          fields:
            - label: "App"
              name: "app"
              widget: "list"
              fields:
                 - {label: "Image", name: "image", widget: "image"}
                 - {label: "Alt text", name: "alt_text", widget: "string"}
        - label: "FAQ"
          name: "faq"
          widget: "object"
          collapsed: true
          fields:
            - {label: "Heading", name: "heading", widget: "string"}
            - {label: "Image", name: "image", widget: "image"}
            - {label: "Alt text", name: "alt_text", widget: "string"}
            - label: "question"
              name: "question"
              widget: "list"
              fields:
                 - {label: "Question", name: "question", widget: "string"}
                 - {label: "Answer", name: "answer", widget: "markdown"}
        - label: "About"
          name: "about"
          widget: "object"
          collapsed: true
            - label: "block"
              name: "block"
              widget: "list"
              fields:
                - {label: "Heading", name: "heading", widget: "string"}
                - {label: "Image", name: "image", widget: "image"}
                - {label: "Alt text", name: "alt_text", widget: "string"}
                - {label: "Text", name: "text", widget: "markdown"}